Optional data binning in shape model
SSDataLab/psfmachine pull request #50
Opened 2022-02-10 19:35 UTC by jorgemarpa

This adds the option of binning the `(dx, dy)` data, taking the median value of `mean_f` if a certain number of bin members are found, or preserving data otherwise. 
This allows fitting a "cleaner" model where the PSF is bright.

Here a generic example:
<img width="883" alt="Screen Shot 2022-02-09 at 13 12 14" src="https://user-images.githubusercontent.com/10449555/153482619-eba2b075-f451-4098-a7e6-0c4ab10e1a77.png">

and a `build_shape_model(bin_data=True)` example
![image](https://user-images.githubusercontent.com/10449555/153482594-759318a1-d779-4013-bceb-13ba1b3f82f7.png)

The new `utils.threshold_binning()` function is early flexible. It allows to change the number of bins, the absolute threshold (number of bin members when taking the median), and use different statistics (e.g. median, mean). 
It takes ~200 ms for a set of 10k data points, that's the typical number of pixels in a ~200 TPF stack. For an FFI with ~100k pixels, it takes ~1.4 s.

2022-02-11 18:59 UTC, christinahedges requested changes
This is great! There are two things that are missing that I think we need before we can merge:

1. We need errors to be propagated. This is because we need to know how much weight to provide each bin when we fit it in the next step. We need to be able to pass errors on `x` and have them be aggregated in a reasonable way. We may want to use a weighted mean for the `statistic`, and use errors on the weighted mean in bins.

We could either pass in 'errors' or 'weights' on each point (we can brainstorm which makes sense).

2. We need some tests of the `threshold_binning` function. Here are a few sketches of what tests might look like

```python

def test_threshold_bin():
    # Pass integers
    x, y, z = 0, 0, 0
    threshold_bin(x, y, z)
    assert ...
    # Pass integer as list
    x, y, z = [0], [0], [0]
    threshold_bin(x, y, z)
    assert ...
    # Pass arrays that are too short
    x, y, z = np.arange(10), np.arange(10), np.ones(10)
    threshold_bin(x, y, z)
    assert ...
    # Pass a bunch of nans
    x, y, z = np.random.normal(size=1000), np.random.normal(size=1000), np.ones(1000) * np.nan
    threshold_bin(x, y, z)
    assert ...
    # Pass something that should actually pass
    x, y, z = np.random.normal(size=1000), np.random.normal(size=1000), np.random.normal(size=1000)
    threshold_bin(x, y, z)
    assert ...
    # Should be a check here that some points are binned, some points are not...

```

2022-02-11 18:59 UTC, christinahedges commented on src/psfmachine/utils.py
> +    xedges = np.linspace(x.min(), x.max(), num=bins[0] + 1)
```suggestion
    xedges = np.linspace(np.nanmin(x), np.nanmax(x), num=bins[0] + 1)
```

2022-02-11 18:59 UTC, christinahedges commented on src/psfmachine/utils.py
> +    yedges = np.linspace(y.min(), y.max(), num=bins[1] + 1)
```suggestion
    yedges = np.linspace(np.nanmin(y), np.nanmax(y), num=bins[1] + 1)
```

2022-02-11 18:59 UTC, christinahedges commented on src/psfmachine/utils.py
> +def threshold_binning(x, y, z, abs_thresh=10, bins=15, statistic=np.nanmedian):
`threshold_binning` might be better as a verb `threshold_bin`?

2022-02-17 23:26 UTC, jorgemarpa commented
New version includes tests and unique function signature when providing or not errors for `z` values.

2022-02-17 23:27 UTC, jorgemarpa commented on src/psfmachine/machine.py
> +            )
the number of bins and threshold need to be defined by the number of uncontaminated pixels.
These numbers I used here are good for an FFI with very dense PSF but don't work with sparse data from a TPF stack.

2022-03-08 18:57 UTC, christinahedges approved these changes
This looks GREAT to me!

2022-03-08 18:57 UTC, christinahedges commented on src/psfmachine/utils.py
> +        bins = [bins, bins]
Maybe do some checks here to ensure that users aren't passing e.g. 1e10 bins

2022-03-08 18:57 UTC, christinahedges commented on src/psfmachine/machine.py
> +            nbins = 30 if mean_f.shape[0] <= 5e3 else 100
Should this be in cartesian coordinates? JMP and CH are discussing

2022-03-08 22:20 UTC, jorgemarpa commented on src/psfmachine/machine.py
> +            )
Set the `nbins` depending on the number of pixels available, for 3 typical ranges.

2022-03-08 22:22 UTC, jorgemarpa commented
@christinahedges I'm happy with the `nbins` depending on how many pixels are in the set. I commented on the explanation to keep track of the hardcoded numbers. 

I think is ready for merging...

2022-03-09 21:03 UTC, merged